options:
  version:
    default: "9.1"
    type: string
    description: Version of PostgreSQL that we want to install
  cluster_name:
    default: "main"
    type: string
    description: Name of the cluster we want to install the DBs into
  kernel_shmall:
    default: 0
    type: int
    description: Kernel/shmall
  kernel_shmmax:
    default: 0
    type: int
    description: Kernel/shmmax
  listen_ip:
    default: "*"
    type: string
    description: IP to listen on
  listen_port:
    default: 5432
    type: int
    description: Port to listen on
  max_connections:
    default: 100
    type: int
    description: Maximum number of connections to allow to the PG database
  ssl:
    default: "True"
    type: string
    description: Whether PostgreSQL should talk SSL
  shared_buffers:
    default: "8MB"
    type: string
    description: Shared buffers
  temp_buffers:
    default: "1MB"
    type: string
    description: Temp buffers
  work_mem:
    default: "1MB"
    type: string
    description: Working Memory
  maintenance_work_mem:
    default: "1MB"
    type: string
    description: Maintenance working memory
  wal_buffers:
    default: "True"
    type: string
    description: WAL buffers 
