options:
  version:
    default: "9.1"
    type: string
    description: Version of PostgreSQL that we want to install
  cluster_name:
    default: "main"
    type: string
    description: Name of the cluster we want to install the DBs into
  kernel_shmall:
    default: 0
    type: int
    description: Kernel/shmall
  kernel_shmmax:
    default: 0
    type: int
    description: Kernel/shmmax
  listen_ip:
    default: "*"
    type: string
    description: IP to listen on
  listen_port:
    default: 5432
    type: int
    description: Port to listen on
  max_connections:
    default: 100
    type: int
    description: Maximum number of connections to allow to the PG database
  ssl:
    default: "True"
    type: string
    description: Whether PostgreSQL should talk SSL
  shared_buffers:
    default: "8MB"
    type: string
    description: Shared buffers
  temp_buffers:
    default: "1MB"
    type: string
    description: Temp buffers
  work_mem:
    default: "1MB"
    type: string
    description: Working Memory
  maintenance_work_mem:
    default: "1MB"
    type: string
    description: Maintenance working memory
  wal_buffers:
    default: "True"
    type: string
    description: WAL buffers 
  checkpoint_segments:
    default: 3
    type: int
    description: in logfile segments, min 1, 16MB each
  random_page_cost:
    default: 4.0
    type: float
    description: Random page cost
  effective_cache_size:
    default: "128MB"
    type: string
    description: Effective cache size
  log_min_duration_statement:
    default: -1
    type: int
    description: |
        -1 is disabled, 0 logs all statements
        and their durations, > 0 logs only
        statements running at least this number
        of milliseconds
  log_checkpoints:
    default: "off"
    type: string
    description: Log checkpoints
  log_connections:
    default: "off"
    type: string
    description: Log connections
  log_disconnections:
    default: "off"
    type: string
    description: Log disconnections
  log_line_prefix:
    default: "%t "
    type: string
    description: |
        special values:
          %a = application name
          %u = user name
          %d = database name
          %r = remote host and port
          %h = remote host
          %p = process ID
          %t = timestamp without milliseconds
          %m = timestamp with milliseconds
          %i = command tag
          %e = SQL state
          %c = session ID
          %l = session line number
          %s = session start timestamp
          %v = virtual transaction ID
          %x = transaction ID (0 if none)
          %q = stop here in non-session processes
          %% = '%'
        e.g. '<%u%%%d> '
  log_lock_waits:
    default: "off"
    type: string
    description: log lock waits >= deadlock_timeout
  log_timezone:
    default: "UTC"
    type: string
    description: Log timezone
  autovacuum:
    default: "on"
    type: string
    description: Autovacuum
  log_autovacuum_min_duration:
    default: -1
    type: int
    description: |
        -1 disables, 0 logs all actions and their durations, > 0 logs only
        actions running at least this number of milliseconds.
  autovacuum_analyze_threshold:
    default: 50
    type: int
    description: min number of row updates before analyze
  autovacuum_vacuum_scale_factor:
    default: 0.2
    type: float
    description: Fraction of table size before vacuum
  autovacuum_analyze_scale_factor:
    default: 0.1  
    type: float
    description: Fraction of table size before analyze
  autovacuum_vacuum_cost_delay:
    default: "20ms"
    type: string
    description: |
        Default vacuum cost delay for autovacuum, in milliseconds;
        -1 means use vacuum_cost_delay
  search_path:
    default: "'\"$user\",public'"
    type: string
    descripton: Schema names
  standard_conforming_strings:
    default: "on"
    type: string
    description: Standard conforming strings
  hot_standby:
    default: ""
    type: string
    description: Hot standby
  hot_standby_feedback:
    default: ""
    type: string
    description: Hot standby feedback
  wal_level:
    default: ""
    type: string
    description: WAL level
  max_wal_senders:
    default: ""
    type: string
    description: WAL level senders
  wal_keep_segments:
    default: ""
    type: string
    description: WAL keep segments
